### ISSUE TITLE
In Signpass API v4 "Invalid JWS Verification" using python ?

### ISSUE THREAD

**Issue by naveenprabhu42** [leeleelee3264/myinfo-connector-python#1]
Hi
![tmp_285b62f7-772e-4306-9b48-78e40f6e1e53](https://github.com/leeleelee3264/myinfo-connector-python/assets/80089161/008a6f56-61ad-4470-acd3-45c10875a092)
![tmp_d1ef3994-38ac-496d-9f44-6f063fe9c87d](https://github.com/leeleelee3264/myinfo-connector-python/assets/80089161/c18091f4-0a06-4b2e-8802-da2598e07bd4)

I'm looking for Singpass Myinfo V4 into our django application. While searching for a python package, I came across one designed for V3. However, I specifically require V4 compatibility. Currently we are building sing pass v4 in python with the reference of myinfo-connector-node.js package we generated client_assertion, Dpop, public signing key, and verified with singpass Api website it's shows verification success but in our application shows "INVALID JWS Verification". I stuck with this error for past few weeks. I would appreciate any suggestions or recommendations.

Thanks

**Comment by leeleelee3264** [comment]
Hi, @naveenprabhu42 
I only did myinfo v3 and have no idea about v4. Sorry for not being helpful.
